apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
    name: keycloak
  name: {{ .Values.rhsso.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.rhsso.service.port }}
    protocol: TCP
    targetPort: {{ .Values.rhsso.service.port }}
  selector:
    app: keycloak
    component: keycloak