apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rhsso
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.rhsso.host }}
  gateways:
  - {{ .Values.rhsso.gateway.name }}
  http:
  - match:
    - prefix:
        exact: /
    route:
    - destination:
        host: {{ .Values.rhsso.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.rhsso.service.port }}